### ISSUE TITLE
Release v0.3.0

### ISSUE THREAD

**Issue by moshe010** [Mellanox/network-operator#124]
## Release Checklist

- [x] Network-operator related component versions in Helm chart are up to date. (otherwise, submit PR to update)
  - [x] node-feature-discovery
  - [x] SR-IOV Network Operator
  - [x] Manifest related component default versions
- [x] Example folder is up to date (otherwise submit PR to update)
- [x] Update network-operator Helm `Chart.yaml` with the release version (`appVersion`, `version` fields)
  - [x] Ensure Helm CI is passing on updated Chart.
- [x] Tag release
- [x] Create a new github release
  - [x] Release title: vx.y.z, Release description: Changelog from this issue
  - [x] Release artifacts for current release
- [x] Update gh-pages branch
  - [x] Create Helm package (master branch on release tag commit):
    ```
        > helm package deployments/network-operator
    ```
  - [x] Place Helm package under gh-pages branch in `release` dir
  - [x] Update `index.yaml` file under gh-pages branch in `release` dir:
    ```
        > helm repo index . --url https://mellanox.github.io/network-operator/release
    ```
  - [x] Update gh-pages branch README.md with `deployment/README.md` from master branch (on release tag commit)
  - [x] Submit PR against `gh-pages` branch:
    ```
        > git add <helm .tgz package> <release/index.yaml> <README.md>
        > git commit --signoff -m "Release Network-Operator vx.y.z"
        > git push ...
    ```
- [x] Add a link to the release in this issue
- [x] Close this issue

### New Features
- [x] Support deploying SR-IOV network operator #58 
- [x] Update go code to operator-sdk 1.3.0 #86 
- [x] Add status printer column for Custom Resources #96 
### Bug Fixes
- [x] Change multus image to v3.6 #101 
- [x] Update helm chart kubeVersion to '>= 1.17.0' #110 
- [x] Use the NFD instance to v0.6.0-233-g3e00bfb #108 
- [x] Update gogo/protobuf to v1.3.2 - CVE-2021-3121 #97 

### Known Limitations
- deploying network operator before gpu operator may cause nv peer mem container to crash
- when deploying mofed pod interface names may change
- mlx_compat module isn't unloaded after kubernetes nicclusterpolicy teardown
- nv-peer-mem container is deployed at master if a GPU is present on it
- mofed container may reset VF node guid which breaks RoCE

**Comment by moshe010** [comment]
https://github.com/Mellanox/network-operator/releases/tag/v0.3.0
