### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by moshe010** [Mellanox/network-operator#137]
## Release Checklist

- [x] Network-operator related component versions in Helm chart are up to date. (otherwise, submit PR to update)
  - [x] node-feature-discovery
  - [x] SR-IOV Network Operator
  - [x] Manifest related component default versions
- [x] Example folder is up to date (otherwise submit PR to update)
- [x] Update network-operator Helm `Chart.yaml` with the release version (`appVersion`, `version` fields)
  - [x] Ensure Helm CI is passing on updated Chart.
- [x] Tag release
- [x] Create a new github release
  - [x] Release title: vx.y.z, Release description: Changelog from this issue
  - [x] Release artifacts for current release
- [x] Update gh-pages branch
  - [x] Create Helm package (master branch on release tag commit):
    ```
        > helm package deployment/network-operator
    ```
  - [x] Place Helm package under gh-pages branch in `release` dir
  - [x] Update `index.yaml` file under gh-pages branch in `release` dir:
    ```
        > # assuming we are under release dir
        > mkdir tmpdir; cp <helm-package.tgz> ./tmpdir
        > helm repo index ./tmpdir --url https://mellanox.github.io/network-operator/release --merge ./index.yaml
        > mv -f ./tmpdir/index.yaml ./; rm -rf ./tmpdir
    ```
  - [x] Update gh-pages branch README.md with `deployment/README.md` from master branch (on release tag commit)
  - [x] Submit PR against `gh-pages` branch:
    ```
        > git add <helm .tgz package> <release/index.yaml> <README.md>
        > git commit -s -m "Release Network-Operator vx.y.z"
        > git push ...
    ```
- [x] Add a link to the release in this issue
- [x] Close this issue

### New Features
- [x] Modify network-operator namespaces #122
- [x] Rename 'devicePlugin' to 'rdmaSharedDevicePlugin' #135 
- [x] Print Age in CR status of all resources #136 
- [x] CRDs are not synced #134 
- [x] Stop using SelfLink #133
- [x] Add linters for helm charts and Dockerfiles #150 
- [x] Add HostDeviceNetwork basic support #126
- [x] Update images for v0.4.0 #153
- [x] Add 'prepare-release.sh' script #149
- [x] Add examples how to configure and deploy SR-IOV network #154

### Bug Fixes
- [x] fix typo in README.md #132
- [x] [helm] fix nfd worker tolerations value #144 
- [x] Add additional nodeAffinity for nv-peer-mem-driver POD #152
- [x] Add support for host OFED to peer-mem POD #155
- [x] update image OFED container image to end of march release

**Comment by e0ne** [comment]
@moshe010 NFD chart doesn't have changes. SR-IOV Network Operator chart has some changes with role settings. Let's sync them early in next release cycle to not introduce last minute issues

**Comment by moshe010** [comment]
mmm, we didn't update NFD version anyway. regarding SR-IOV operator I assume you test it with the current crd, right?
if there are no issue with that we can release it as is

**Comment by e0ne** [comment]
It works with current version because we adjust RBAC configuration

**Comment by e0ne** [comment]
New release is published: https://github.com/Mellanox/network-operator/releases/tag/v0.4.0
