### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by moshe010** [Mellanox/network-operator#162]
## Release Checklist

- [x] Network-operator related component versions in Helm chart are up to date. (otherwise, submit PR to update)
  - [x] node-feature-discovery
  - [x] SR-IOV Network Operator
  - [x] Manifest related component default versions
- [x] Example folder is up to date (otherwise submit PR to update)
- [x] Update network-operator Helm `Chart.yaml` with the release version (`appVersion`, `version` fields)
  ```
       > ./scripts/releases/prepare-release.sh v0.1.2 "Jane Doe <jane.doe@example.com>"
  ```
  - [x] Ensure Helm CI is passing on updated Chart.
- [x] Tag release
- [x] Create a new github release
  - [x] Release title: vx.y.z, Release description: Changelog from this issue
  - [x] Release artifacts for current release
- [x] Update gh-pages branch
  ```
       > ./scripts/releases/update-gh-pages.sh network-operator-0.1.2.tgz
  ```
  - [x] Create Helm package (master branch on release tag commit):
    ```
        > helm package deployment/network-operator
    ```
  - [x] Place Helm package under gh-pages branch in `release` dir
  - [x] Update `index.yaml` file under gh-pages branch in `release` dir:
    ```
        > # assuming we are under release dir
        > mkdir tmpdir; cp <helm-package.tgz> ./tmpdir
        > helm repo index ./tmpdir --url https://mellanox.github.io/network-operator/release --merge ./index.yaml
        > mv -f ./tmpdir/index.yaml ./; rm -rf ./tmpdir
    ```
  - [x] Update gh-pages branch README.md with `deployment/README.md` from master branch (on release tag commit)
  - [x] Submit PR against `gh-pages` branch:
    ```
        > git add <helm .tgz package> <release/index.yaml> <README.md>
        > git commit -s -m "Release Network-Operator vx.y.z"
        > git push ...
    ```
- [x] Add a link to the release in this issue
- [x] Close this issue

### New Features
- [x] Use upstream NFD chart #160
- [x] Add OpenShift deployment support #94
- [x] Update nv-peer-mem-driver to 1.1-0  

### Bug Fixes
- [x] Change order of networking components rendering #159
- [x] Add notes about compatibility with gpu-operator #161
- [x] Increase terminationGracePeriodSeconds for OFED POD #164
- [x] Fix typo in an example file name #163
- [x] Network Operator deploys networking components (Multus CNI, CNI Plugins and Whereabout) before MOFED
- [x] Use Kubernetes-specific image for SR-IOV Network operator by default #167 
- [x] Network Operator components work as expected after node reboot
- [x] Fix pods deployment order after cluster scale-up

 

### Known Limitations

- Network Operator is compatible with NVIDIA GPU Operator v1.5.2 and above

**Comment by e0ne** [comment]
New GitHub release and tag created: https://github.com/Mellanox/network-operator/releases/tag/v0.5.0
