### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by e0ne** [Mellanox/network-operator#176]
## Release Checklist

- [x] Network-operator related component versions in Helm chart are up to date. (otherwise, submit PR to update)
  - [x] node-feature-discovery
  - [x] SR-IOV Network Operator
  - [x] Manifest related component default versions
- [x] Example folder is up to date (otherwise submit PR to update)
- [x] Update network-operator Helm `Chart.yaml` with the release version (`appVersion`, `version` fields)
  ```
       > ./scripts/releases/prepare-release.sh v0.1.2 "Jane Doe <jane.doe@example.com>"
  ```
  - [x] Ensure Helm CI is passing on updated Chart.
- [x] Tag release
- [x] Create a new github release
  - [x] Release title: vx.y.z, Release description: Changelog from this issue
  - [x] Release artifacts for current release
- [x] Update gh-pages branch
  ```
       > ./scripts/releases/update-gh-pages.sh network-operator-0.1.2.tgz
  ```
  - [ ] Create Helm package (master branch on release tag commit):
    ```
        > helm package deployment/network-operator
    ```
  - [x] Place Helm package under gh-pages branch in `release` dir
  - [ ] Update `index.yaml` file under gh-pages branch in `release` dir:
    ```
        > # assuming we are under release dir
        > mkdir tmpdir; cp <helm-package.tgz> ./tmpdir
        > helm repo index ./tmpdir --url https://mellanox.github.io/network-operator/release --merge ./index.yaml
        > mv -f ./tmpdir/index.yaml ./; rm -rf ./tmpdir
    ```
  - [ ] Update gh-pages branch README.md with `deployment/README.md` from master branch (on release tag commit)
  - [ ] Submit PR against `gh-pages` branch:
    ```
        > git add <helm .tgz package> <release/index.yaml> <README.md>
        > git commit -s -m "Release Network-Operator vx.y.z"
        > git push ...
    ```
- [ ] Add a link to the release in this issue
- [ ] Close this issue

### New Features

- [x] nv per mem support in GPU Driver #191
- [x] scale up support
- [x] [helm chart] Images configuration #105
### Bug Fixes

- [x] Failure to deploy mofed on a single node in cluster will halt deployment progress #184
- [x] Network Operator fails to update node labels #182
- [x] When deploying mofed pod interface names change
- [x] When deploying mofed pod interfaces become in down state

**Comment by e0ne** [comment]
New release is created https://github.com/Mellanox/network-operator/releases/tag/v0.6.0
